### ISSUE TITLE
Please add "Gamepads.start()" to the "Usage" paragraph in readme

### ISSUE THREAD

**Issue by jonaspetersorensen** [FThompson/Gamepads.js#1]
A (very) small thing, but I got stuck for a while until I read through the code and realized that you use a `start` method to get things going. 

How about adding `start` in the Usage example like this:
```js
// Start polling
Gamepads.start();

// Add event handlers
Gamepads.addEventListener...
```

EDIT: ....and now I see that you have a nice API reference as well where this is documented.

Pretty neat stuff, thanks for sharing it :)

**Comment by FThompson** [comment]
Sorry you had to spend time figuring that out, I'll add that to the usage example shortly. Thanks!
